import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  deserts,
  mountains,
  NATURAL_LAYER_DEFS,
  rivers,
  type NaturalAreaFeature,
  type NaturalLinearFeature,
} from '../src/data/naturalFeatures';

type Position = [number, number];

function assertPosition(position: Position, featureId: string) {
  const [lng, lat] = position;
  if (!Number.isFinite(lng) || !Number.isFinite(lat)) {
    throw new Error(`Feature ${featureId} contains non-finite coordinate: [${lng}, ${lat}]`);
  }
  if (lng < -180 || lng > 180) {
    throw new Error(`Feature ${featureId} longitude out of bounds: ${lng}`);
  }
  if (lat < -90 || lat > 90) {
    throw new Error(`Feature ${featureId} latitude out of bounds: ${lat}`);
  }
}

function validateLinear(features: NaturalLinearFeature[]) {
  const seen = new Set<string>();
  for (const feature of features) {
    if (seen.has(feature.id)) {
      throw new Error(`Duplicate linear feature id: ${feature.id}`);
    }
    seen.add(feature.id);
    if (feature.coordinates.length < 2) {
      throw new Error(`Linear feature ${feature.id} must contain at least 2 coordinates`);
    }
    feature.coordinates.forEach((p) => assertPosition(p, feature.id));
  }
}

function validateAreas(features: NaturalAreaFeature[]) {
  const seen = new Set<string>();
  for (const feature of features) {
    if (seen.has(feature.id)) {
      throw new Error(`Duplicate area feature id: ${feature.id}`);
    }
    seen.add(feature.id);
    if (!feature.polygon.length) {
      throw new Error(`Area feature ${feature.id} must include at least one ring`);
    }
    for (const ring of feature.polygon) {
      if (ring.length < 4) {
        throw new Error(`Area feature ${feature.id} has a ring with fewer than 4 points`);
      }
      ring.forEach((p) => assertPosition(p, feature.id));
      const first = ring[0];
      const last = ring[ring.length - 1];
      if (first[0] !== last[0] || first[1] !== last[1]) {
        throw new Error(`Area feature ${feature.id} ring is not closed`);
      }
    }
  }
}

function toTsConst<T>(value: T) {
  return JSON.stringify(value, null, 2);
}

function buildGeneratedModule() {
  return `// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: npm run build:natural-data

export type NaturalFeatureCategory = 'rivers' | 'mountains' | 'deserts';

export interface NaturalLinearFeature {
  id: string;
  name: string;
  category: 'rivers' | 'mountains';
  description?: string;
  coordinates: [number, number][];
}

export interface NaturalAreaFeature {
  id: string;
  name: string;
  category: 'deserts';
  description?: string;
  polygon: [number, number][][];
}

export interface NaturalLayerDef {
  id: NaturalFeatureCategory;
  label: string;
  color: string;
  description: string;
}

export const NATURAL_LAYER_DEFS: NaturalLayerDef[] = ${toTsConst(NATURAL_LAYER_DEFS)};

export const rivers: NaturalLinearFeature[] = ${toTsConst(rivers)};

export const mountains: NaturalLinearFeature[] = ${toTsConst(mountains)};

export const deserts: NaturalAreaFeature[] = ${toTsConst(deserts)};
`;
}

function buildSourceGeoJson() {
  const features = [
    ...rivers.map((r) => ({
      type: 'Feature',
      id: r.id,
      properties: {
        name: r.name,
        category: r.category,
        description: r.description ?? null,
      },
      geometry: {
        type: 'LineString',
        coordinates: r.coordinates,
      },
    })),
    ...mountains.map((m) => ({
      type: 'Feature',
      id: m.id,
      properties: {
        name: m.name,
        category: m.category,
        description: m.description ?? null,
      },
      geometry: {
        type: 'LineString',
        coordinates: m.coordinates,
      },
    })),
    ...deserts.map((d) => ({
      type: 'Feature',
      id: d.id,
      properties: {
        name: d.name,
        category: d.category,
        description: d.description ?? null,
      },
      geometry: {
        type: 'Polygon',
        coordinates: d.polygon,
      },
    })),
  ];

  return {
    type: 'FeatureCollection',
    metadata: {
      generatedAt: new Date().toISOString(),
      note: 'Seed source extracted from src/data/naturalFeatures.ts',
    },
    features,
  };
}

async function main() {
  validateLinear(rivers);
  validateLinear(mountains);
  validateAreas(deserts);

  const __filename = fileURLToPath(import.meta.url);
  const __dirname = path.dirname(__filename);
  const projectRoot = path.resolve(__dirname, '..');

  const generatedPath = path.join(projectRoot, 'src/data/naturalFeatures.generated.ts');
  const rawDir = path.join(projectRoot, 'data-raw/natural');
  const rawGeoJsonPath = path.join(rawDir, 'natural-features.seed.geojson');

  await mkdir(rawDir, { recursive: true });
  await writeFile(generatedPath, buildGeneratedModule(), 'utf8');
  await writeFile(rawGeoJsonPath, `${JSON.stringify(buildSourceGeoJson(), null, 2)}\n`, 'utf8');

  // Keep output concise for CI logs.
  console.log('natural features generated');
}

void main();
