// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by: npm run build:natural-data

export type NaturalFeatureCategory = 'rivers' | 'mountains' | 'deserts';

export interface NaturalLinearFeature {
  id: string;
  name: string;
  category: 'rivers' | 'mountains';
  description?: string;
  coordinates: [number, number][];
}

export interface NaturalAreaFeature {
  id: string;
  name: string;
  category: 'deserts';
  description?: string;
  polygon: [number, number][][];
}

export interface NaturalLayerDef {
  id: NaturalFeatureCategory;
  label: string;
  color: string;
  description: string;
}

export const NATURAL_LAYER_DEFS: NaturalLayerDef[] = [
  {
    "id": "rivers",
    "label": "Major Rivers",
    "color": "#4fc3f7",
    "description": "Major river systems that form natural borders and strategic waterways"
  },
  {
    "id": "mountains",
    "label": "Mountain Ranges",
    "color": "#a1887f",
    "description": "Major mountain ranges that form natural barriers and borders"
  },
  {
    "id": "deserts",
    "label": "Deserts",
    "color": "#d4a853",
    "description": "Major desert regions that form natural barriers"
  }
];

export const rivers: NaturalLinearFeature[] = [
  {
    "id": "river-amazon",
    "name": "Amazon",
    "category": "rivers",
    "description": "Largest river by discharge; forms border segments between Peru, Colombia, and Brazil",
    "coordinates": [
      [
        -76,
        -10
      ],
      [
        -74.5,
        -8.5
      ],
      [
        -72,
        -7
      ],
      [
        -70,
        -4.5
      ],
      [
        -68,
        -3.5
      ],
      [
        -65,
        -3
      ],
      [
        -62,
        -3.2
      ],
      [
        -60,
        -3
      ],
      [
        -58,
        -3.5
      ],
      [
        -56,
        -2.5
      ],
      [
        -54,
        -2
      ],
      [
        -52,
        -1.8
      ],
      [
        -50.5,
        -0.5
      ]
    ]
  },
  {
    "id": "river-nile",
    "name": "Nile",
    "category": "rivers",
    "description": "Longest river; shapes the border between Sudan and Ethiopia, and defines Egypt",
    "coordinates": [
      [
        32.5,
        -1
      ],
      [
        31.8,
        4
      ],
      [
        32.5,
        9
      ],
      [
        33,
        14
      ],
      [
        33.5,
        18
      ],
      [
        32.5,
        22
      ],
      [
        32,
        26
      ],
      [
        31.2,
        30
      ]
    ]
  },
  {
    "id": "river-congo",
    "name": "Congo",
    "category": "rivers",
    "description": "Forms much of the border between DRC and Republic of Congo",
    "coordinates": [
      [
        26.5,
        -6
      ],
      [
        25,
        -4.5
      ],
      [
        23.5,
        -2.5
      ],
      [
        21,
        -1
      ],
      [
        19,
        0.5
      ],
      [
        17.5,
        1.5
      ],
      [
        16.5,
        1
      ],
      [
        15.5,
        -1.5
      ],
      [
        13,
        -4
      ],
      [
        12.3,
        -5.8
      ]
    ]
  },
  {
    "id": "river-niger",
    "name": "Niger",
    "category": "rivers",
    "description": "Defines borders of Mali, Niger, Benin, and Nigeria",
    "coordinates": [
      [
        -10.5,
        12
      ],
      [
        -5,
        14.5
      ],
      [
        0,
        16
      ],
      [
        3.5,
        17
      ],
      [
        4.5,
        15.5
      ],
      [
        6,
        14
      ],
      [
        7.5,
        11.5
      ],
      [
        8,
        9.5
      ],
      [
        6,
        7
      ],
      [
        4.5,
        5.5
      ]
    ]
  },
  {
    "id": "river-zambezi",
    "name": "Zambezi",
    "category": "rivers",
    "description": "Forms borders between Zambia, Zimbabwe, Namibia, and Botswana",
    "coordinates": [
      [
        22,
        -11.5
      ],
      [
        24.5,
        -14
      ],
      [
        26.5,
        -14.5
      ],
      [
        28,
        -15.5
      ],
      [
        30,
        -17
      ],
      [
        32.5,
        -17.5
      ],
      [
        34.5,
        -17.8
      ],
      [
        35.8,
        -17
      ]
    ]
  },
  {
    "id": "river-yangtze",
    "name": "Yangtze",
    "category": "rivers",
    "description": "Longest river in Asia; historical cultural and strategic divide in China",
    "coordinates": [
      [
        91,
        32.5
      ],
      [
        96,
        33
      ],
      [
        100,
        30
      ],
      [
        103.5,
        29
      ],
      [
        106.5,
        29.5
      ],
      [
        109.5,
        30.5
      ],
      [
        112.5,
        30
      ],
      [
        114.5,
        30.5
      ],
      [
        117,
        30.8
      ],
      [
        119.5,
        30.5
      ],
      [
        121.5,
        31.3
      ]
    ]
  },
  {
    "id": "river-mekong",
    "name": "Mekong",
    "category": "rivers",
    "description": "Forms the border between Myanmar/Laos and Thailand/China",
    "coordinates": [
      [
        94.5,
        28
      ],
      [
        98,
        24.5
      ],
      [
        100,
        22
      ],
      [
        101.5,
        19.5
      ],
      [
        102.5,
        18
      ],
      [
        104,
        16.5
      ],
      [
        105,
        14
      ],
      [
        106,
        12
      ],
      [
        106.8,
        10.5
      ]
    ]
  },
  {
    "id": "river-danube",
    "name": "Danube",
    "category": "rivers",
    "description": "Forms borders between 10 European countries including Romania, Bulgaria, and Serbia",
    "coordinates": [
      [
        8.5,
        48
      ],
      [
        13,
        48.5
      ],
      [
        17,
        48
      ],
      [
        19.5,
        47.5
      ],
      [
        22,
        46.5
      ],
      [
        24.5,
        45.5
      ],
      [
        27,
        45.2
      ],
      [
        29,
        46.5
      ],
      [
        30.5,
        46
      ]
    ]
  },
  {
    "id": "river-rhine",
    "name": "Rhine",
    "category": "rivers",
    "description": "Forms the border between Germany and France; historically contested",
    "coordinates": [
      [
        9,
        47
      ],
      [
        8.5,
        47.8
      ],
      [
        7.5,
        48.5
      ],
      [
        7.8,
        49.5
      ],
      [
        7.5,
        50.5
      ],
      [
        7,
        51
      ],
      [
        6.5,
        51.8
      ],
      [
        4.5,
        52.5
      ]
    ]
  },
  {
    "id": "river-rio-grande",
    "name": "Rio Grande",
    "category": "rivers",
    "description": "Forms the entire US–Mexico border from El Paso to the Gulf of Mexico",
    "coordinates": [
      [
        -106.5,
        31.8
      ],
      [
        -104,
        30
      ],
      [
        -103,
        29.5
      ],
      [
        -100.5,
        29
      ],
      [
        -99,
        28
      ],
      [
        -97.5,
        26.5
      ],
      [
        -97,
        25.8
      ]
    ]
  },
  {
    "id": "river-mississippi",
    "name": "Mississippi",
    "category": "rivers",
    "description": "Major North American river system; historical US interior waterway",
    "coordinates": [
      [
        -95,
        47
      ],
      [
        -93,
        44.5
      ],
      [
        -91.5,
        42
      ],
      [
        -91,
        40
      ],
      [
        -90.5,
        38
      ],
      [
        -89.5,
        36
      ],
      [
        -90,
        33.5
      ],
      [
        -90.5,
        31
      ],
      [
        -89.5,
        29
      ]
    ]
  },
  {
    "id": "river-amur",
    "name": "Amur",
    "category": "rivers",
    "description": "Forms the border between Russia and China (Manchuria)",
    "coordinates": [
      [
        112,
        53.5
      ],
      [
        116,
        53
      ],
      [
        120,
        52.5
      ],
      [
        124,
        52
      ],
      [
        127.5,
        50.5
      ],
      [
        130.5,
        48.5
      ],
      [
        133.5,
        47.5
      ],
      [
        134.5,
        48.4
      ]
    ]
  },
  {
    "id": "river-jordan",
    "name": "Jordan",
    "category": "rivers",
    "description": "Forms the border between Israel/West Bank and Jordan",
    "coordinates": [
      [
        35.7,
        33.2
      ],
      [
        35.5,
        32.5
      ],
      [
        35.5,
        31.8
      ],
      [
        35.6,
        31
      ],
      [
        35.6,
        31.5
      ]
    ]
  },
  {
    "id": "river-ganges",
    "name": "Ganges",
    "category": "rivers",
    "description": "Sacred river of the Indian subcontinent; culturally divides northern India",
    "coordinates": [
      [
        78.5,
        30.5
      ],
      [
        79.5,
        29
      ],
      [
        80.5,
        27.5
      ],
      [
        82,
        26.5
      ],
      [
        84.5,
        26
      ],
      [
        86.5,
        25.5
      ],
      [
        88.5,
        24.5
      ],
      [
        89.5,
        24
      ],
      [
        90.5,
        23.5
      ]
    ]
  }
];

export const mountains: NaturalLinearFeature[] = [
  {
    "id": "mt-himalayas",
    "name": "Himalayas",
    "category": "mountains",
    "description": "World's highest range; forms the border between India, Nepal, Bhutan, and China",
    "coordinates": [
      [
        72.5,
        34
      ],
      [
        75,
        33.5
      ],
      [
        78,
        33
      ],
      [
        80.5,
        32
      ],
      [
        84,
        28.5
      ],
      [
        86.5,
        28
      ],
      [
        89,
        27.5
      ],
      [
        92,
        28
      ],
      [
        96,
        28.5
      ]
    ]
  },
  {
    "id": "mt-karakoram",
    "name": "Karakoram",
    "category": "mountains",
    "description": "Contains K2; borders Pakistan, China, and the disputed Kashmir region",
    "coordinates": [
      [
        73.5,
        36.5
      ],
      [
        75.5,
        36.8
      ],
      [
        77.5,
        36.5
      ],
      [
        78.5,
        35.5
      ]
    ]
  },
  {
    "id": "mt-hindu-kush",
    "name": "Hindu Kush",
    "category": "mountains",
    "description": "Separates Central Asia from the South Asian subcontinent; spans Afghanistan and Pakistan",
    "coordinates": [
      [
        62,
        36.5
      ],
      [
        65,
        36.5
      ],
      [
        67.5,
        36
      ],
      [
        70,
        36
      ],
      [
        72.5,
        36.5
      ]
    ]
  },
  {
    "id": "mt-alps",
    "name": "Alps",
    "category": "mountains",
    "description": "Forms borders between France, Switzerland, Italy, and Austria",
    "coordinates": [
      [
        6.5,
        45
      ],
      [
        8,
        46
      ],
      [
        9.5,
        46.5
      ],
      [
        11,
        47
      ],
      [
        12.5,
        47.5
      ],
      [
        14,
        47.5
      ],
      [
        15.5,
        47
      ]
    ]
  },
  {
    "id": "mt-caucasus",
    "name": "Caucasus",
    "category": "mountains",
    "description": "Forms the border between Russia and Georgia/Azerbaijan; divides Europe and Asia",
    "coordinates": [
      [
        37.5,
        43.5
      ],
      [
        40,
        43.5
      ],
      [
        42.5,
        43.2
      ],
      [
        45,
        42.5
      ],
      [
        47,
        41.5
      ]
    ]
  },
  {
    "id": "mt-andes",
    "name": "Andes",
    "category": "mountains",
    "description": "Forms the spine of South America and borders between Chile, Argentina, Bolivia, Peru, Colombia",
    "coordinates": [
      [
        -73,
        10.5
      ],
      [
        -76,
        5
      ],
      [
        -78.5,
        0
      ],
      [
        -79,
        -5
      ],
      [
        -79,
        -10
      ],
      [
        -75.5,
        -15
      ],
      [
        -72,
        -20
      ],
      [
        -68,
        -25
      ],
      [
        -67.5,
        -30
      ],
      [
        -70,
        -35
      ],
      [
        -71.5,
        -40
      ],
      [
        -72.5,
        -45
      ],
      [
        -73.5,
        -50
      ],
      [
        -74.5,
        -55
      ]
    ]
  },
  {
    "id": "mt-rockies",
    "name": "Rocky Mountains",
    "category": "mountains",
    "description": "North American cordillera; forms the continental divide",
    "coordinates": [
      [
        -136,
        60
      ],
      [
        -130,
        56
      ],
      [
        -122,
        50
      ],
      [
        -116,
        46
      ],
      [
        -112,
        42
      ],
      [
        -107,
        38
      ],
      [
        -105.5,
        34
      ],
      [
        -104,
        31.5
      ]
    ]
  },
  {
    "id": "mt-atlas",
    "name": "Atlas Mountains",
    "category": "mountains",
    "description": "Separates the Mediterranean coast from the Sahara in Morocco, Algeria, and Tunisia",
    "coordinates": [
      [
        -6,
        35.5
      ],
      [
        -3,
        34.5
      ],
      [
        0.5,
        33.5
      ],
      [
        3,
        33.5
      ],
      [
        6,
        34
      ],
      [
        9.5,
        37
      ]
    ]
  },
  {
    "id": "mt-urals",
    "name": "Ural Mountains",
    "category": "mountains",
    "description": "Traditional geographic boundary between Europe and Asia",
    "coordinates": [
      [
        60.5,
        69
      ],
      [
        60,
        64
      ],
      [
        59.5,
        60
      ],
      [
        58.5,
        56
      ],
      [
        57,
        52
      ],
      [
        55.5,
        51
      ]
    ]
  },
  {
    "id": "mt-zagros",
    "name": "Zagros Mountains",
    "category": "mountains",
    "description": "Forms border between Iran, Iraq, and Turkey; shields the Iranian plateau",
    "coordinates": [
      [
        38.5,
        37.5
      ],
      [
        42,
        36
      ],
      [
        44,
        34
      ],
      [
        46,
        32
      ],
      [
        48.5,
        30
      ],
      [
        50,
        27.5
      ]
    ]
  },
  {
    "id": "mt-great-dividing",
    "name": "Great Dividing Range",
    "category": "mountains",
    "description": "Australia's primary mountain range; divides coastal Australia from the interior",
    "coordinates": [
      [
        145,
        -15.5
      ],
      [
        144.5,
        -18
      ],
      [
        144,
        -22
      ],
      [
        148,
        -26
      ],
      [
        151,
        -29
      ],
      [
        151.5,
        -32
      ],
      [
        150,
        -35
      ],
      [
        148.5,
        -37.5
      ],
      [
        148,
        -39
      ]
    ]
  },
  {
    "id": "mt-pyrenees",
    "name": "Pyrenees",
    "category": "mountains",
    "description": "Forms the border between France and Spain",
    "coordinates": [
      [
        -1.8,
        43.5
      ],
      [
        0.5,
        43
      ],
      [
        2,
        42.5
      ],
      [
        3.5,
        42.5
      ]
    ]
  },
  {
    "id": "mt-carpathians",
    "name": "Carpathians",
    "category": "mountains",
    "description": "Arc of mountains through Central Europe; bounds Hungary and forms Slovakia/Romania borders",
    "coordinates": [
      [
        17,
        49.5
      ],
      [
        19.5,
        49.5
      ],
      [
        22,
        49
      ],
      [
        24.5,
        49.5
      ],
      [
        26.5,
        48.5
      ],
      [
        27,
        47.5
      ],
      [
        25.5,
        46
      ],
      [
        24,
        45.5
      ]
    ]
  },
  {
    "id": "mt-tian-shan",
    "name": "Tian Shan",
    "category": "mountains",
    "description": "Forms borders between Kazakhstan, Kyrgyzstan, and China",
    "coordinates": [
      [
        70,
        43
      ],
      [
        74,
        43.5
      ],
      [
        77.5,
        43
      ],
      [
        80,
        42.5
      ],
      [
        82.5,
        41.5
      ],
      [
        85.5,
        41
      ],
      [
        88.5,
        42
      ]
    ]
  }
];

export const deserts: NaturalAreaFeature[] = [
  {
    "id": "desert-sahara",
    "name": "Sahara",
    "category": "deserts",
    "description": "World's largest hot desert; defines North Africa and separates Sub-Saharan Africa",
    "polygon": [
      [
        [
          -17,
          20.5
        ],
        [
          -5,
          17.5
        ],
        [
          0,
          16
        ],
        [
          5,
          17.5
        ],
        [
          10,
          20
        ],
        [
          15,
          23.5
        ],
        [
          20,
          25
        ],
        [
          25,
          28.5
        ],
        [
          30,
          29
        ],
        [
          34,
          27.5
        ],
        [
          37,
          24
        ],
        [
          36,
          20.5
        ],
        [
          33,
          18.5
        ],
        [
          28,
          17.5
        ],
        [
          20,
          16.5
        ],
        [
          12,
          16
        ],
        [
          5,
          15.5
        ],
        [
          0,
          14
        ],
        [
          -5,
          15
        ],
        [
          -10,
          17
        ],
        [
          -15,
          19.5
        ],
        [
          -17,
          20.5
        ]
      ]
    ]
  },
  {
    "id": "desert-arabian",
    "name": "Arabian Desert",
    "category": "deserts",
    "description": "Covers most of the Arabian Peninsula; strategic energy region",
    "polygon": [
      [
        [
          36.5,
          29.5
        ],
        [
          40.5,
          28
        ],
        [
          45,
          22.5
        ],
        [
          50,
          20
        ],
        [
          55,
          22.5
        ],
        [
          59,
          23.5
        ],
        [
          60.5,
          24.5
        ],
        [
          60,
          28
        ],
        [
          57.5,
          30
        ],
        [
          55,
          32
        ],
        [
          50,
          30.5
        ],
        [
          46,
          30.5
        ],
        [
          42,
          31.5
        ],
        [
          38.5,
          31.5
        ],
        [
          36.5,
          29.5
        ]
      ]
    ]
  },
  {
    "id": "desert-gobi",
    "name": "Gobi",
    "category": "deserts",
    "description": "Cold desert spanning northern China and southern Mongolia",
    "polygon": [
      [
        [
          90,
          42
        ],
        [
          96,
          42.5
        ],
        [
          102,
          42
        ],
        [
          107,
          44
        ],
        [
          112,
          46.5
        ],
        [
          117,
          48.5
        ],
        [
          120,
          48
        ],
        [
          122,
          46.5
        ],
        [
          120,
          43
        ],
        [
          116,
          40.5
        ],
        [
          111,
          39
        ],
        [
          106,
          38.5
        ],
        [
          100,
          38
        ],
        [
          94,
          38.5
        ],
        [
          90,
          40
        ],
        [
          90,
          42
        ]
      ]
    ]
  },
  {
    "id": "desert-kalahari",
    "name": "Kalahari",
    "category": "deserts",
    "description": "Semi-arid desert spanning Botswana, Namibia, and South Africa",
    "polygon": [
      [
        [
          18.5,
          -18
        ],
        [
          22,
          -18
        ],
        [
          25,
          -19
        ],
        [
          27.5,
          -20.5
        ],
        [
          28,
          -24
        ],
        [
          27,
          -27.5
        ],
        [
          24,
          -29.5
        ],
        [
          21,
          -29
        ],
        [
          18.5,
          -27.5
        ],
        [
          17,
          -24
        ],
        [
          18,
          -20
        ],
        [
          18.5,
          -18
        ]
      ]
    ]
  },
  {
    "id": "desert-namib",
    "name": "Namib",
    "category": "deserts",
    "description": "Coastal desert along the Atlantic shore of Namibia and Angola",
    "polygon": [
      [
        [
          12.5,
          -17.5
        ],
        [
          14,
          -17.5
        ],
        [
          16.5,
          -19
        ],
        [
          17.5,
          -22
        ],
        [
          17.5,
          -26
        ],
        [
          16.5,
          -29
        ],
        [
          15.5,
          -30.5
        ],
        [
          14.5,
          -30
        ],
        [
          13,
          -27
        ],
        [
          12,
          -23
        ],
        [
          12,
          -19
        ],
        [
          12.5,
          -17.5
        ]
      ]
    ]
  },
  {
    "id": "desert-atacama",
    "name": "Atacama",
    "category": "deserts",
    "description": "World's driest non-polar desert; coastal Chile and Peru",
    "polygon": [
      [
        [
          -70.5,
          -18
        ],
        [
          -68.5,
          -17.5
        ],
        [
          -67,
          -19
        ],
        [
          -67,
          -23
        ],
        [
          -68,
          -26.5
        ],
        [
          -70.5,
          -28.5
        ],
        [
          -71,
          -26
        ],
        [
          -70.5,
          -22
        ],
        [
          -70.5,
          -18
        ]
      ]
    ]
  },
  {
    "id": "desert-great-victoria",
    "name": "Australian Desert",
    "category": "deserts",
    "description": "Includes the Great Victoria, Gibson, and Great Sandy deserts",
    "polygon": [
      [
        [
          116,
          -24
        ],
        [
          121,
          -23.5
        ],
        [
          126,
          -23.5
        ],
        [
          130,
          -25
        ],
        [
          134,
          -26.5
        ],
        [
          136.5,
          -30
        ],
        [
          133,
          -32
        ],
        [
          129,
          -32
        ],
        [
          124.5,
          -32
        ],
        [
          120,
          -30.5
        ],
        [
          117,
          -27.5
        ],
        [
          116,
          -24
        ]
      ]
    ]
  },
  {
    "id": "desert-taklamakan",
    "name": "Taklamakan",
    "category": "deserts",
    "description": "Large desert in China's Xinjiang region; a historic barrier along the Silk Road",
    "polygon": [
      [
        [
          76,
          40.5
        ],
        [
          80,
          40.5
        ],
        [
          84,
          40
        ],
        [
          88,
          40.5
        ],
        [
          90,
          40.5
        ],
        [
          91.5,
          39.5
        ],
        [
          90.5,
          37.5
        ],
        [
          88,
          37
        ],
        [
          84,
          37
        ],
        [
          80,
          37.5
        ],
        [
          77.5,
          38.5
        ],
        [
          76,
          39.5
        ],
        [
          76,
          40.5
        ]
      ]
    ]
  },
  {
    "id": "desert-iranian",
    "name": "Iranian Plateau Deserts",
    "category": "deserts",
    "description": "Dasht-e Kavir and Dasht-e Lut; central Iran's salt deserts",
    "polygon": [
      [
        [
          51,
          36.5
        ],
        [
          54,
          36
        ],
        [
          57.5,
          36
        ],
        [
          60,
          35
        ],
        [
          61,
          33
        ],
        [
          60.5,
          30.5
        ],
        [
          58,
          28.5
        ],
        [
          55,
          29.5
        ],
        [
          52,
          30.5
        ],
        [
          50,
          32.5
        ],
        [
          50.5,
          34.5
        ],
        [
          51,
          36.5
        ]
      ]
    ]
  },
  {
    "id": "desert-patagonian",
    "name": "Patagonian Desert",
    "category": "deserts",
    "description": "Cold desert in southern Argentina; sits in rain shadow of the Andes",
    "polygon": [
      [
        [
          -68.5,
          -38.5
        ],
        [
          -66,
          -38
        ],
        [
          -64,
          -38.5
        ],
        [
          -63.5,
          -41
        ],
        [
          -64,
          -44
        ],
        [
          -65,
          -47
        ],
        [
          -66,
          -50
        ],
        [
          -67.5,
          -51.5
        ],
        [
          -69,
          -50
        ],
        [
          -70,
          -47
        ],
        [
          -70.5,
          -44
        ],
        [
          -70,
          -41
        ],
        [
          -68.5,
          -38.5
        ]
      ]
    ]
  }
];
